import { NextPage } from "next";
import Head from "next/head";
import Home from "./landing-page";
import NavbarComponent from "@/components/Navbar";
import Footer from "@/components/Footer";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>bogor-mengabdi-v2</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>

      <NavbarComponent />
      <Home />
      <Footer />
    </>
  );
};

export default Index;
